modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/SrRapero720/watermedia/issues"
[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/watermedia"
    logoFile="pack.png" #optional
    credits="VLC to VideoLAN team, VLCJ by caprica, VLCJ discovery by CreativeMD"
    authors="${mod_authors}"
    description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"# ON FORGE ONLY SUPPORTS 1.17 (MIN JAVA IS 15 FEATURES)
    ordering="NONE"
    side="CLIENT"